[package]
name = "ura"
version = "1.0.0"
authors = ["Ura"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.15" }
cosmwasm-std = { version = "1.1.5" }
uint = "0.9"
cw-storage-plus = "0.15"
itertools = "0.10"
cosmwasm-schema = "1.1"
cw-utils = "1.0"
cw3 = "1.0"
cw20-base = { version = "0.15", features = ["library"] }

# optional
thiserror = { version = "1.0", optional = true }

[dev-dependencies]
test-case = "3.1.0"
