[package]
name = "ura_mock"
version = "1.0.0"
authors = ["Ura"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw20 = { version = "0.15" }
cosmwasm-std = { version = "1.1.5" }
ura = { path = "../ura", default-features = false }
